### PR TITLE
add Linux build

### PR DESCRIPTION
**Pull request by spiralw**
This adds `linux/` directory with (mostly) files generated by flutter. I just changed the package name in `CMakeLists.txt`

### CODE REVIEW

**Comment by drwankingstein** [comment]
commit reorg p8 lowercase file names - c5371832fd5caef8871fca3b93c08c13de207864 broke this it does work on the previous commit however

**Comment by NO-ob** [comment]
thanks, did you have any luck with video playback working, it has been broken on my system for a while

**Comment by drwankingstein** [comment]
> did you have any luck with video playback working, it has been broken on my system for a while

that sometimes happens when modifying it. only solution I have found is to do a fresh re-clone and build, I can't say for sure but I think flutter tool isn't cleaning build files properly and they get corrupted

**Comment by NANI-SORE** [comment]
PhotoView is for interactivity (zoom, pan...), the NaN error is probably related to a code which tries to get video dimensions for better zooming.
I copied it from mobile player, but now that I think about it, it's not necessary here, will remove in next commit.
The main problem with videos is that current video handler for desktop is just a placeholder while we wait for official video support from google, I don't want to go too deep into fixing it when it's possible that we'll just drop it completely

**Pull request merged**
