### PR TITLE
Improved viewer, experimental caching, fixes

### PR DESCRIPTION
**Pull request by NANI-SORE**
- overhauled viewer, thanks to photo_view - double tap to zoom support, panning doesn't break page changing and images don't overlap
- highly experimental image caching (only for thumbnails for now), can be cleared in settings
- show booru icon near each tab option
- share button (currently just sends direct url, not the file itself)

### CODE REVIEW

**Comment by NO-ob** [comment]
Hi sorry for only just seeing this, I will take a look and merge tomorrow when I can

**Comment by NANI-SORE** [comment]
No problem. I see that this PR now has some conflicts, nothing big thankfully - move loadingGif to MediaViewer, and merge pubspec. I can do it later today myself and resend PR. I also added more things since this commit.
Can I add you somewhere like telegram/discord? It would be easier to cooperate that way

**Comment by NO-ob** [comment]
My discord is NO_ob#9642 whats yours?

**Comment by NANI-SORE** [comment]
NaniDeagle#8517

**Pull request merged**
